package ua.kpi.ipze.ontology.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import ua.kpi.ipze.ontology.entity.AutoGeneratedOntology;
import ua.kpi.ipze.ontology.repository.AutoGeneratedOntologyRepository;

import java.util.List;

@Service
@RequiredArgsConstructor
public class AutoGeneratedOntologyService {
    private final AutoGeneratedOntologyRepository autoGeneratedOntologyRepository;

    public List<AutoGeneratedOntology> getAutogeneratedOntologies(){
        return autoGeneratedOntologyRepository.findAll();
    }
}
